In [1]:
!pip install numpy

In [3]:
import numpy as np

In [5]:
n= np.array((1,2,3,4))
print(n)

[1 2 3 4]


In [7]:
print(type(n))

<class 'numpy.ndarray'>


In [9]:
import numpy as np

# Define two matrices
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Matrix Addition
addition_result = A + B
print("Matrix Addition:\n", addition_result)

# Matrix Subtraction
subtraction_result = A - B
print("\nMatrix Subtraction:\n", subtraction_result)

# Matrix Multiplication (Element-wise)
multiplication_result = A * B
print("\nElement-wise Matrix Multiplication:\n", multiplication_result)

# Matrix Dot Product
dot_product_result = np.dot(A, B)
print("\nMatrix Dot Product:\n", dot_product_result)

# Transpose of a Matrix
transpose_A = A.T
print("\nTranspose of Matrix A:\n", transpose_A)

# Determinant of a Matrix
det_A = np.linalg.det(A)
print("\nDeterminant of Matrix A:", det_A)


Matrix Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Subtraction:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Element-wise Matrix Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix Dot Product:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Transpose of Matrix A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

Determinant of Matrix A: -9.51619735392994e-16


In [11]:
import pandas as pd

# Create a simple dataset
data = {
    "Student": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Math_Score": [85, 78, 92, 88, 76],
    "Science_Score": [90, 82, 95, 89, 80],
    "English_Score": [88, 79, 85, 90, 84]
}

df = pd.DataFrame(data)
print("Initial Data Table:\n", df)

# Filter rows where Math_Score is greater than 80
high_math_scores = df[df["Math_Score"] > 80]
print("\nStudents with Math Score > 80:\n", high_math_scores)

# Add a new column for the average score
df["Average_Score"] = df[["Math_Score", "Science_Score", "English_Score"]].mean(axis=1)
print("\nData Table with Average Score:\n", df)

# Calculate basic statistics
mean_scores = df.mean(numeric_only=True)
median_scores = df.median(numeric_only=True)
print("\nMean Scores:\n", mean_scores)
print("\nMedian Scores:\n", median_scores)


Initial Data Table:
    Student  Math_Score  Science_Score  English_Score
0    Alice          85             90             88
1      Bob          78             82             79
2  Charlie          92             95             85
3    David          88             89             90
4     Emma          76             80             84

Students with Math Score > 80:
    Student  Math_Score  Science_Score  English_Score
0    Alice          85             90             88
2  Charlie          92             95             85
3    David          88             89             90

Data Table with Average Score:
    Student  Math_Score  Science_Score  English_Score  Average_Score
0    Alice          85             90             88      87.666667
1      Bob          78             82             79      79.666667
2  Charlie          92             95             85      90.666667
3    David          88             89             90      89.000000
4     Emma          76             80      